import { ICookProfile, IMaidProfile, ICustomerReview, ServiceType } from '../types';

export interface IPopularService {
  id: string;
  title: string;
  category: 'maid' | 'cook' | 'cleaning';
  badge: string;
  description: string;
  price: string;
  rating: number;
  reviewsCount: number;
  image: string;
  features: string[];
}

export interface IMainServiceCard {
  id: string;
  title: string;
  subtitle: string;
  tag: string;
  description: string;
  image: string;
  startingPrice: string;
  features: string[];
  serviceType: ServiceType;
}

export interface IFaqItem {
  id: string;
  question: string;
  answer: string;
  category: string;
}

export const MOCK_MAIN_SERVICES: IMainServiceCard[] = [
  {
    id: 'main-cook',
    title: 'Professional Home Cook',
    subtitle: 'Delicious & Hygienic Homemade Meals',
    tag: 'Popular',
    description: 'Expert chefs & traditional cooks for daily breakfast, lunch, and dinner. Customized menu for North Indian, South Indian, Regional, Keto & Diet needs.',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
    startingPrice: '₹250/meal',
    features: ['Customized Menu', 'Hygiene Assured', 'Dietary & Jain Friendly', 'Party Catering Option'],
    serviceType: ServiceType.COOK,
  },
  {
    id: 'main-maid',
    title: 'Trusted House Maid',
    subtitle: 'Sparkling Clean Home Everyday',
    tag: 'Essential',
    description: 'Police-verified housemaids for floor mopping, dusting, utensil cleaning, bathroom sanitization, laundry and wardrobe organization.',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80',
    startingPrice: '₹180/hr',
    features: ['100% Police Verified', 'Utensil Washing', 'Laundry & Ironing', 'Daily / Monthly Slots'],
    serviceType: ServiceType.MAID,
  },
  {
    id: 'main-combo',
    title: 'Cook + Maid Combo',
    subtitle: 'Complete Home Care Solution',
    tag: 'Best Value (Save 20%)',
    description: 'Get a dedicated cook and maid pair for full home management. Enjoy delicious meals and a spotless home without managing multiple staff.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    startingPrice: '₹7,999/mo',
    features: ['Dedicated Dual Staff', 'Priority Replacement', 'Single Invoice Billing', 'Full Day Coverage'],
    serviceType: ServiceType.BOTH,
  },
];

export const MOCK_POPULAR_SERVICES: IPopularService[] = [
  {
    id: 'pop-1',
    title: 'Daily Maid Service',
    category: 'maid',
    badge: 'Most Booked',
    description: 'Daily 1-2 hours cleaning, dishwashing & sweeping for hassle-free home maintenance.',
    price: '₹2,499/month',
    rating: 4.9,
    reviewsCount: 1420,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=400&q=80',
    features: ['Floor Mopping', 'Dish Washing', 'Dusting'],
  },
  {
    id: 'pop-2',
    title: 'Part Time Maid',
    category: 'maid',
    badge: 'Flexible',
    description: 'On-demand 2-4 hours assistance for laundry, deep kitchen cleanup & balcony washing.',
    price: '₹199/hour',
    rating: 4.8,
    reviewsCount: 980,
    image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=400&q=80',
    features: ['Flexi Slots', 'Weekend Special', 'Ironing'],
  },
  {
    id: 'pop-3',
    title: 'Full Time Maid',
    category: 'maid',
    badge: '24x7 / 8-Hour',
    description: 'Dedicated full-day housekeeping & family support with verified background credentials.',
    price: '₹14,999/month',
    rating: 4.95,
    reviewsCount: 650,
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=400&q=80',
    features: ['8-12 Hours Shift', 'All House Tasks', 'Dedicated Staff'],
  },
  {
    id: 'pop-4',
    title: 'Pure Veg Cook',
    category: 'cook',
    badge: 'High Hygiene',
    description: 'Specialist in North Indian, South Indian, Gujarati & Jain pure vegetarian cooking.',
    price: '₹3,499/month',
    rating: 4.9,
    reviewsCount: 1850,
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=400&q=80',
    features: ['Separate Utensils', 'Jain Options', 'Fresh Roti/Rice'],
  },
  {
    id: 'pop-5',
    title: 'Non Veg Cook',
    category: 'cook',
    badge: 'Gourmet Chefs',
    description: 'Delicious Biryani, Mughlai, Seafood, Coastal & Continental dishes cooked at your home kitchen.',
    price: '₹3,999/month',
    rating: 4.88,
    reviewsCount: 1210,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
    features: ['Rich Curries', 'BBQ & Seafood', 'Party Special'],
  },
  {
    id: 'pop-6',
    title: 'Deep House Cleaning',
    category: 'cleaning',
    badge: '100% Sanitized',
    description: 'Comprehensive deep cleaning of bathrooms, kitchen, windows, sofa & balcony with machine tools.',
    price: '₹1,499/service',
    rating: 4.92,
    reviewsCount: 2100,
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=400&q=80',
    features: ['Industrial Scrubbing', 'Sofa Shampooing', 'Tile Descaling'],
  },
];

// ==========================================
// 25 UNIQUE COOK PROFILES
// ==========================================
export const MOCK_COOKS: ICookProfile[] = [
  {
    id: 'cook-1',
    userId: 'u-101',
    name: 'Chef Ramesh Kumar',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=300&q=80',
    bio: 'Specialist in North Indian, South Indian & Jain Delicacies with 8+ years experience in premium catering.',
    experienceYears: 8,
    serviceTypes: [ServiceType.COOK],
    skills: ['North Indian', 'South Indian', 'Diet Meals', 'Sweets'],
    languages: ['Hindi', 'English', 'Punjabi'],
    averageRating: 4.9,
    totalRatings: 128,
    completedBookings: 340,
    isAvailable: true,
    hourlyRate: 350,
    monthlyRate: 7500,
    city: 'Bengaluru',
    area: 'Indiranagar',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-2',
    userId: 'u-102',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Expert home cook specializing in Healthy Home Cooked Thali, Gujarati, and Keto Meal Plans.',
    experienceYears: 5,
    serviceTypes: [ServiceType.COOK],
    skills: ['Home Thali', 'Gujarati', 'Keto & Vegan', 'Breakfast'],
    languages: ['Hindi', 'Gujarati', 'English'],
    averageRating: 4.8,
    totalRatings: 94,
    completedBookings: 210,
    isAvailable: true,
    hourlyRate: 280,
    monthlyRate: 6000,
    city: 'Bengaluru',
    area: 'Koramangala',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-3',
    userId: 'u-103',
    name: 'Chef Anthony D’Souza',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Master of Continental, Indo-Chinese & Goan Seafood specialties for family dinners and party hosting.',
    experienceYears: 10,
    serviceTypes: [ServiceType.COOK],
    skills: ['Continental', 'Indo-Chinese', 'Seafood', 'Party Catering'],
    languages: ['English', 'Hindi', 'Konkani'],
    averageRating: 4.95,
    totalRatings: 156,
    completedBookings: 480,
    isAvailable: false,
    hourlyRate: 450,
    monthlyRate: 9500,
    city: 'Mumbai',
    area: 'Bandra West',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-4',
    userId: 'u-104',
    name: 'Sunita Patel',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Traditional Gujarati and Rajasthani pure vegetarian cook with 7 years of high hygiene kitchen experience.',
    experienceYears: 7,
    serviceTypes: [ServiceType.COOK],
    skills: ['Gujarati Thali', 'Rajasthani Dal Baati', 'Jain Special', 'Snacks'],
    languages: ['Hindi', 'Gujarati'],
    averageRating: 4.85,
    totalRatings: 110,
    completedBookings: 310,
    isAvailable: true,
    hourlyRate: 300,
    monthlyRate: 6500,
    city: 'Mumbai',
    area: 'Andheri West',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-5',
    userId: 'u-105',
    name: 'Venkatesh Rao',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Authentic South Indian Tiffin & meals expert: Crisp Dosa, Idli, Sambar, Andhra Spice Rice & Filter Coffee.',
    experienceYears: 6,
    serviceTypes: [ServiceType.COOK],
    skills: ['South Indian', 'Andhra Spice Meals', 'Filter Coffee', 'Tiffin'],
    languages: ['Telugu', 'Kannada', 'Tamil', 'English'],
    averageRating: 4.78,
    totalRatings: 88,
    completedBookings: 240,
    isAvailable: true,
    hourlyRate: 260,
    monthlyRate: 5800,
    city: 'Bengaluru',
    area: 'Whitefield',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-6',
    userId: 'u-106',
    name: 'Manpreet Kaur',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=300&q=80',
    bio: 'Punjabi Dhaba style authentic Butter Chicken, Amritsari Kulcha, Rajma Chawal & Sarson ka Saag Specialist.',
    experienceYears: 9,
    serviceTypes: [ServiceType.COOK],
    skills: ['Punjabi Cuisine', 'Tandoori Parathas', 'Mughlai', 'Rich Gravies'],
    languages: ['Punjabi', 'Hindi', 'English'],
    averageRating: 4.92,
    totalRatings: 175,
    completedBookings: 420,
    isAvailable: true,
    hourlyRate: 380,
    monthlyRate: 8200,
    city: 'Delhi NCR',
    area: 'Gurugram Sec 56',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-7',
    userId: 'u-107',
    name: 'Chef Kabir Khan',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
    bio: 'Authentic Hyderabadi Dum Biryani, Galouti Kebab, and Mughlai Feast Specialist for events & daily meals.',
    experienceYears: 12,
    serviceTypes: [ServiceType.COOK],
    skills: ['Hyderabadi Biryani', 'Mughlai Kebabs', 'Mutton Specialties', 'Desserts'],
    languages: ['Hindi', 'Urdu', 'English'],
    averageRating: 4.96,
    totalRatings: 210,
    completedBookings: 590,
    isAvailable: false,
    hourlyRate: 500,
    monthlyRate: 11000,
    city: 'Hyderabad',
    area: 'Banjara Hills',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-8',
    userId: 'u-108',
    name: 'Lata Deshmukh',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80',
    bio: 'Traditional Maharashtrian home-style cook. Expert in Puran Poli, Misal, Pitla Bhakri & Malvani Fish Curry.',
    experienceYears: 6,
    serviceTypes: [ServiceType.COOK],
    skills: ['Maharashtrian', 'Malvani Seafood', 'Puran Poli', 'Snacks'],
    languages: ['Marathi', 'Hindi'],
    averageRating: 4.82,
    totalRatings: 92,
    completedBookings: 230,
    isAvailable: true,
    hourlyRate: 270,
    monthlyRate: 5800,
    city: 'Pune',
    area: 'Kothrud',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-9',
    userId: 'u-109',
    name: 'Chef Subhashish Ghosh',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    bio: 'Authentic Bengali Fish Curry, Kosha Mangsho, Mishti Doi & Luchi Alur Dom Specialist.',
    experienceYears: 8,
    serviceTypes: [ServiceType.COOK],
    skills: ['Bengali Cuisine', 'Fish Curry', 'Sweets & Payesh', 'Indo-Chinese'],
    languages: ['Bengali', 'Hindi', 'English'],
    averageRating: 4.88,
    totalRatings: 134,
    completedBookings: 370,
    isAvailable: true,
    hourlyRate: 340,
    monthlyRate: 7200,
    city: 'Kolkata',
    area: 'Salt Lake',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-10',
    userId: 'u-110',
    name: 'Geetha Swaminathan',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    bio: 'Tamil Brahmin & Chettinad Home Cook. Specializes in healthy millet meals, Rasam, Sambar & Poriyal.',
    experienceYears: 7,
    serviceTypes: [ServiceType.COOK],
    skills: ['Chettinad', 'Brahmin Pure Veg', 'Millet Meals', 'Sambar & Rasam'],
    languages: ['Tamil', 'English', 'Hindi'],
    averageRating: 4.84,
    totalRatings: 105,
    completedBookings: 290,
    isAvailable: true,
    hourlyRate: 290,
    monthlyRate: 6200,
    city: 'Chennai',
    area: 'T. Nagar',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-11',
    userId: 'u-111',
    name: 'Suresh Kumar',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    bio: 'Multi-cuisine family cook specializing in healthy low-oil North Indian & Chinese dishes for daily home meals.',
    experienceYears: 4,
    serviceTypes: [ServiceType.COOK],
    skills: ['North Indian', 'Chinese Noodles', 'Low Oil Cooking', 'Breakfast'],
    languages: ['Hindi', 'English'],
    averageRating: 4.7,
    totalRatings: 62,
    completedBookings: 180,
    isAvailable: true,
    hourlyRate: 240,
    monthlyRate: 5200,
    city: 'Delhi NCR',
    area: 'Noida Sector 62',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-12',
    userId: 'u-112',
    name: 'Reena Joshi',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    bio: 'Specialist in Kid-friendly nutritious meals, school tiffin prep, and organic healthy salads & soups.',
    experienceYears: 5,
    serviceTypes: [ServiceType.COOK],
    skills: ['Kids Meals', 'Organic Soups & Salads', 'Healthy Pastas', 'Baking'],
    languages: ['Hindi', 'English', 'Marathi'],
    averageRating: 4.87,
    totalRatings: 84,
    completedBookings: 205,
    isAvailable: true,
    hourlyRate: 310,
    monthlyRate: 6700,
    city: 'Pune',
    area: 'Viman Nagar',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-13',
    userId: 'u-113',
    name: 'Chef Arjun Reddy',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    bio: 'Telangana & Andhra spicy meat curries, Biryani & Royyala Iguru (Prawn Fry) specialist.',
    experienceYears: 9,
    serviceTypes: [ServiceType.COOK],
    skills: ['Andhra Non-Veg', 'Hyderabadi Pulao', 'Seafood Fry', 'BBQ Grill'],
    languages: ['Telugu', 'Hindi', 'English'],
    averageRating: 4.91,
    totalRatings: 148,
    completedBookings: 410,
    isAvailable: true,
    hourlyRate: 400,
    monthlyRate: 8800,
    city: 'Hyderabad',
    area: 'Gachibowli',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-14',
    userId: 'u-114',
    name: 'Kavita Nair',
    avatar: 'https://images.unsplash.com/photo-1563306406-e66174fa3787?auto=format&fit=crop&w=300&q=80',
    bio: 'Authentic Kerala Sadya, Fish Moilee, Appam & Stew, and Coconut-infused coastal curries.',
    experienceYears: 6,
    serviceTypes: [ServiceType.COOK],
    skills: ['Kerala Cuisine', 'Coastal Fish Curry', 'Appam & Stew', 'Ayurvedic Meals'],
    languages: ['Malayalam', 'English', 'Hindi', 'Tamil'],
    averageRating: 4.89,
    totalRatings: 98,
    completedBookings: 270,
    isAvailable: true,
    hourlyRate: 330,
    monthlyRate: 7000,
    city: 'Bengaluru',
    area: 'HSR Layout',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-15',
    userId: 'u-115',
    name: 'Deepak Verma',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    bio: 'Quick 2-hour daily meal preparation for working couples. Punctual, neat, and diet-conscious.',
    experienceYears: 4,
    serviceTypes: [ServiceType.COOK],
    skills: ['Daily Roti Sabzi', 'Quick Meals', 'Dal Tadka', 'Fitness Meals'],
    languages: ['Hindi', 'English'],
    averageRating: 4.75,
    totalRatings: 70,
    completedBookings: 190,
    isAvailable: true,
    hourlyRate: 250,
    monthlyRate: 5500,
    city: 'Delhi NCR',
    area: 'South Extension',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-16',
    userId: 'u-116',
    name: 'Alka Mehta',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=300&q=80',
    bio: 'Jain & Satvik pure vegetarian cooking expert. Zero garlic/onion meals with authentic traditional flavors.',
    experienceYears: 8,
    serviceTypes: [ServiceType.COOK],
    skills: ['Satvik Veg', 'Jain Cooking', 'Gujarati Sweets', 'High Hygiene'],
    languages: ['Gujarati', 'Hindi'],
    averageRating: 4.93,
    totalRatings: 130,
    completedBookings: 350,
    isAvailable: true,
    hourlyRate: 320,
    monthlyRate: 6800,
    city: 'Mumbai',
    area: 'Ghatkopar East',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-17',
    userId: 'u-117',
    name: 'Chef Rajesh Sharma',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    bio: 'Hotel management trained home chef specializing in Italian Pastas, Pizzas, and Fusion Dinner Parties.',
    experienceYears: 11,
    serviceTypes: [ServiceType.COOK],
    skills: ['Italian & Pasta', 'Woodfire Pizza', 'Continental', 'Dessert Plating'],
    languages: ['English', 'Hindi'],
    averageRating: 4.97,
    totalRatings: 180,
    completedBookings: 490,
    isAvailable: false,
    hourlyRate: 480,
    monthlyRate: 10500,
    city: 'Bengaluru',
    area: 'UB City / Lavelle Rd',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-18',
    userId: 'u-118',
    name: 'Sushma Sen',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Healthy high-protein diet meals cook for bodybuilders, gym-goers & senior citizens.',
    experienceYears: 5,
    serviceTypes: [ServiceType.COOK],
    skills: ['High Protein Diet', 'Steamed Meals', 'Keto Salads', 'Low Sodium'],
    languages: ['Bengali', 'Hindi', 'English'],
    averageRating: 4.81,
    totalRatings: 78,
    completedBookings: 220,
    isAvailable: true,
    hourlyRate: 290,
    monthlyRate: 6200,
    city: 'Kolkata',
    area: 'Park Street',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-19',
    userId: 'u-119',
    name: 'Vikram Singh',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Traditional Rajasthani Royal Thali & Marwari home food. Laal Maas, Gatte ki Sabzi & Churma.',
    experienceYears: 9,
    serviceTypes: [ServiceType.COOK],
    skills: ['Rajasthani Royal', 'Marwari Thali', 'Bati Churma', 'Non-Veg Gravy'],
    languages: ['Hindi', 'Rajasthani'],
    averageRating: 4.9,
    totalRatings: 142,
    completedBookings: 380,
    isAvailable: true,
    hourlyRate: 360,
    monthlyRate: 7800,
    city: 'Delhi NCR',
    area: 'Dwarka Sec 12',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-20',
    userId: 'u-120',
    name: 'Pooja Hegde',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Mangalorean Coastal Fish & Chicken Curry, Neer Dosa & Kori Rotti home cooking specialist.',
    experienceYears: 6,
    serviceTypes: [ServiceType.COOK],
    skills: ['Mangalorean', 'Neer Dosa', 'Ghee Roast', 'Coastal Seafood'],
    languages: ['Kannada', 'Tulu', 'Hindi', 'English'],
    averageRating: 4.86,
    totalRatings: 102,
    completedBookings: 280,
    isAvailable: true,
    hourlyRate: 320,
    monthlyRate: 6900,
    city: 'Bengaluru',
    area: 'JP Nagar',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-21',
    userId: 'u-121',
    name: 'Manoj Kumar',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
    bio: 'Simple home-style North Indian meals: Phulke, Arhar Dal, Bhindi Fry, Kheer & Raita.',
    experienceYears: 3,
    serviceTypes: [ServiceType.COOK],
    skills: ['Home Style North Indian', 'Phulka Roti', 'Dal Chawal'],
    languages: ['Hindi'],
    averageRating: 4.65,
    totalRatings: 45,
    completedBookings: 140,
    isAvailable: true,
    hourlyRate: 220,
    monthlyRate: 4800,
    city: 'Pune',
    area: 'Hinjewadi Phase 1',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-22',
    userId: 'u-122',
    name: 'Anita Roy',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=300&q=80',
    bio: 'Specialist in East Indian & Assamese delicacies, bamboo shoot pork/chicken & mustard fish.',
    experienceYears: 6,
    serviceTypes: [ServiceType.COOK],
    skills: ['North-East Specialties', 'Mustard Fish', 'Herbal Soups'],
    languages: ['Assamese', 'Bengali', 'English', 'Hindi'],
    averageRating: 4.83,
    totalRatings: 86,
    completedBookings: 230,
    isAvailable: true,
    hourlyRate: 300,
    monthlyRate: 6400,
    city: 'Kolkata',
    area: 'New Town',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-23',
    userId: 'u-123',
    name: 'Chef Imran Qureshi',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Awadhi & Lucknowi Dum Biryani, Shahi Tukda & Nihari specialist for weekend family feasts.',
    experienceYears: 10,
    serviceTypes: [ServiceType.COOK],
    skills: ['Awadhi Dum Biryani', 'Kebabs', 'Mughlai Sweets'],
    languages: ['Hindi', 'Urdu', 'English'],
    averageRating: 4.94,
    totalRatings: 168,
    completedBookings: 460,
    isAvailable: true,
    hourlyRate: 420,
    monthlyRate: 9200,
    city: 'Delhi NCR',
    area: 'Vasant Kunj',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'cook-24',
    userId: 'u-124',
    name: 'Shalini Sundaram',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    bio: 'Authentic Kerala Coconut Curry, Karimeen Pollichathu & Malabar Parotta specialist.',
    experienceYears: 7,
    serviceTypes: [ServiceType.COOK],
    skills: ['Malabar Non-Veg', 'Parotta & Curry', 'Payasam Sweets'],
    languages: ['Malayalam', 'Tamil', 'English'],
    averageRating: 4.88,
    totalRatings: 115,
    completedBookings: 320,
    isAvailable: true,
    hourlyRate: 330,
    monthlyRate: 7100,
    city: 'Chennai',
    area: 'Adyar',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'cook-25',
    userId: 'u-125',
    name: 'Pradeep Jadhav',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    bio: 'Kolhapuri Tambda Rassa, Pandhra Rassa & spicy mutton fry home cook.',
    experienceYears: 8,
    serviceTypes: [ServiceType.COOK],
    skills: ['Kolhapuri Non-Veg', 'Spicy Curries', 'Bhakri Roti'],
    languages: ['Marathi', 'Hindi'],
    averageRating: 4.89,
    totalRatings: 124,
    completedBookings: 340,
    isAvailable: true,
    hourlyRate: 310,
    monthlyRate: 6700,
    city: 'Mumbai',
    area: 'Thane West',
    gender: 'Male',
    verified: true,
  },
];

// ==========================================
// 25 UNIQUE MAID PROFILES
// ==========================================
export const MOCK_MAIDS: IMaidProfile[] = [
  {
    id: 'maid-1',
    userId: 'u-201',
    name: 'Sunita Devi',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    bio: 'Professional housemaid with expertise in deep cleaning, utensil washing, and organized housekeeping.',
    experienceYears: 6,
    services: ['Deep Cleaning', 'Utensil Washing', 'Dusting & Mopping', 'Kitchen Organization'],
    skills: ['Sanitization', 'Eco-friendly Products', 'Punctual & Thorough'],
    languages: ['Hindi', 'Kannada'],
    averageRating: 4.85,
    totalRatings: 112,
    completedBookings: 390,
    isAvailable: true,
    hourlyRate: 220,
    monthlyRate: 3500,
    city: 'Bengaluru',
    area: 'Indiranagar',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-2',
    userId: 'u-202',
    name: 'Lakshmi Narayan',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    bio: 'Trustworthy, police-verified maid for daily home maintenance, laundry, ironing, and floor care.',
    experienceYears: 4,
    services: ['Daily Cleaning', 'Laundry & Ironing', 'Bathroom Sanitization'],
    skills: ['Fabric Care', 'High Hygiene Standards', 'Pet-friendly'],
    languages: ['Hindi', 'Telugu', 'Kannada'],
    averageRating: 4.75,
    totalRatings: 86,
    completedBookings: 245,
    isAvailable: true,
    hourlyRate: 200,
    monthlyRate: 3200,
    city: 'Bengaluru',
    area: 'Koramangala',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-3',
    userId: 'u-203',
    name: 'Meena Rao',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80',
    bio: 'Specialized deep cleaning expert for move-in/move-out, post-party cleanup, and festive home renewal.',
    experienceYears: 7,
    services: ['Deep House Cleaning', 'Post-Party Cleanup', 'Window & Balcony Washing'],
    skills: ['Deep Scrubbing', 'Appliance Cleaning', 'Efficiency'],
    languages: ['Hindi', 'English', 'Marathi'],
    averageRating: 4.9,
    totalRatings: 140,
    completedBookings: 410,
    isAvailable: true,
    hourlyRate: 260,
    monthlyRate: 4200,
    city: 'Mumbai',
    area: 'Bandra West',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-4',
    userId: 'u-204',
    name: 'Sarita Kumari',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Efficient 2-hour daily morning maid for floor mopping, dishwashing, and trash disposal.',
    experienceYears: 5,
    services: ['Floor Mopping', 'Dish Washing', 'Dusting', 'Trash Removal'],
    skills: ['Fast Work', 'Punctual', 'Respectful'],
    languages: ['Hindi'],
    averageRating: 4.8,
    totalRatings: 95,
    completedBookings: 280,
    isAvailable: true,
    hourlyRate: 190,
    monthlyRate: 3000,
    city: 'Delhi NCR',
    area: 'Noida Sec 50',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-5',
    userId: 'u-205',
    name: 'Radha Rani',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Full-time 8-hour live-in or day maid for complete household chores, baby care & elderly help.',
    experienceYears: 8,
    services: ['Full Time Maid', 'Elderly Assistance', 'Baby Care', 'Laundry'],
    skills: ['Patient', 'Experienced', 'Multi-tasker'],
    languages: ['Hindi', 'Bengali'],
    averageRating: 4.92,
    totalRatings: 160,
    completedBookings: 450,
    isAvailable: false,
    hourlyRate: 300,
    monthlyRate: 14000,
    city: 'Kolkata',
    area: 'Ballygunge',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-6',
    userId: 'u-206',
    name: 'Ramu Shinde',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Heavy home cleaning specialist: Window glass polishing, terrace washing, sofa shampooing & carpet vacuuming.',
    experienceYears: 6,
    services: ['Heavy Cleaning', 'Carpet Vacuuming', 'Glass Cleaning', 'Terrace Scrubbing'],
    skills: ['Machine Cleaning', 'Physical Stamina', 'Hard Worker'],
    languages: ['Marathi', 'Hindi'],
    averageRating: 4.84,
    totalRatings: 104,
    completedBookings: 310,
    isAvailable: true,
    hourlyRate: 250,
    monthlyRate: 4000,
    city: 'Pune',
    area: 'Aundh',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'maid-7',
    userId: 'u-207',
    name: 'Anusuiya Amma',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=300&q=80',
    bio: 'Gentle and reliable maid for South Indian households. Excellent at brass item polishing & traditional home care.',
    experienceYears: 10,
    services: ['Daily Cleaning', 'Utensil Scrubbing', 'Pooja Room Cleaning', 'Ironing'],
    skills: ['Traditional Care', 'Pooja Polishing', 'Quiet & Gentle'],
    languages: ['Kannada', 'Tamil', 'Telugu'],
    averageRating: 4.95,
    totalRatings: 185,
    completedBookings: 520,
    isAvailable: true,
    hourlyRate: 240,
    monthlyRate: 3800,
    city: 'Bengaluru',
    area: 'Jayanagar',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-8',
    userId: 'u-208',
    name: 'Pooja Sharma',
    avatar: 'https://images.unsplash.com/photo-1563306406-e66174fa3787?auto=format&fit=crop&w=300&q=80',
    bio: 'Pet-friendly house maid specializing in pet hair removal, sofa vacuuming, and apartment maintenance.',
    experienceYears: 4,
    services: ['Pet Hair Cleaning', 'Sofa Vacuuming', 'Dusting', 'Floor Disinfection'],
    skills: ['Pet-friendly', 'Vacuum Handling', 'Disinfection'],
    languages: ['Hindi', 'English'],
    averageRating: 4.79,
    totalRatings: 78,
    completedBookings: 210,
    isAvailable: true,
    hourlyRate: 210,
    monthlyRate: 3300,
    city: 'Delhi NCR',
    area: 'Gurugram Sec 43',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-9',
    userId: 'u-209',
    name: 'Champa Bai',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=300&q=80',
    bio: 'Thorough kitchen cleaning expert: Chimney degreasing, microwave cleaning & cabinet organizing.',
    experienceYears: 7,
    services: ['Kitchen Deep Clean', 'Chimney Degreasing', 'Appliance Scrubbing', 'Cabinet Org'],
    skills: ['Kitchen Degreasing', 'Organized', 'Thorough'],
    languages: ['Hindi', 'Gujarati'],
    averageRating: 4.88,
    totalRatings: 122,
    completedBookings: 360,
    isAvailable: true,
    hourlyRate: 230,
    monthlyRate: 3600,
    city: 'Mumbai',
    area: 'Malad West',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-10',
    userId: 'u-210',
    name: 'Gowriamma',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Dedicated morning 1-hour utensil and dusting maid for small apartments & bachelor flats.',
    experienceYears: 5,
    services: ['Dishwashing', 'Dusting', 'Trash Disposal'],
    skills: ['Quick Service', 'Reliable', 'Honest'],
    languages: ['Tamil', 'Telugu'],
    averageRating: 4.72,
    totalRatings: 65,
    completedBookings: 195,
    isAvailable: true,
    hourlyRate: 180,
    monthlyRate: 2800,
    city: 'Chennai',
    area: 'Velachery',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-11',
    userId: 'u-211',
    name: 'Kamla Devi',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    bio: 'Expert in laundry folding, machine washing, bedsheet changing, and wardrobe organization.',
    experienceYears: 6,
    services: ['Laundry Washing', 'Ironing', 'Wardrobe Org', 'Bedsheet Change'],
    skills: ['Garment Care', 'Fabric Folding', 'Neatness'],
    languages: ['Hindi'],
    averageRating: 4.83,
    totalRatings: 98,
    completedBookings: 290,
    isAvailable: true,
    hourlyRate: 200,
    monthlyRate: 3200,
    city: 'Hyderabad',
    area: 'Miyapur',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-12',
    userId: 'u-212',
    name: 'Ganesh Shinde',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
    bio: 'Post-construction and renovation house scrubbing & dust removal specialist.',
    experienceYears: 5,
    services: ['Post Construction Clean', 'Paint Stain Removal', 'Tile Descaling'],
    skills: ['Heavy Duty', 'Stain Removal', 'Machine Polishing'],
    languages: ['Marathi', 'Hindi'],
    averageRating: 4.81,
    totalRatings: 74,
    completedBookings: 220,
    isAvailable: true,
    hourlyRate: 270,
    monthlyRate: 4500,
    city: 'Pune',
    area: 'Wakad',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'maid-13',
    userId: 'u-213',
    name: 'Savitri Bai',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    bio: 'Bathroom sanitization and tile descaling specialist. Leaves bathrooms germ-free & sparkling.',
    experienceYears: 8,
    services: ['Bathroom Descaling', 'Tile Scrubbing', 'Sanitization', 'Mirror Shine'],
    skills: ['Deep Sanitization', 'Acid/Scale Cleaning', 'Hygiene'],
    languages: ['Hindi', 'Kannada'],
    averageRating: 4.91,
    totalRatings: 138,
    completedBookings: 390,
    isAvailable: true,
    hourlyRate: 230,
    monthlyRate: 3600,
    city: 'Bengaluru',
    area: 'Electronic City',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-14',
    userId: 'u-214',
    name: 'Kusum Lata',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80',
    bio: 'Punctual daily maid for luxury high-rise gated societies with biometrics clearance.',
    experienceYears: 5,
    services: ['Daily Cleaning', 'Mopping', 'Utensils', 'Balcony Sweep'],
    skills: ['Society Verified', 'Punctual', 'Polite'],
    languages: ['Hindi', 'English'],
    averageRating: 4.78,
    totalRatings: 82,
    completedBookings: 240,
    isAvailable: true,
    hourlyRate: 210,
    monthlyRate: 3400,
    city: 'Delhi NCR',
    area: 'Indirapuram',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-15',
    userId: 'u-215',
    name: 'Manjula K',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=300&q=80',
    bio: 'Daily morning & evening double shift maid for large family villas & duplex homes.',
    experienceYears: 9,
    services: ['Villa Housekeeping', 'Floor Mopping', 'Dishes', 'Dusting'],
    skills: ['Large Home Care', 'Thorough', 'Polite'],
    languages: ['Telugu', 'Kannada', 'Hindi'],
    averageRating: 4.93,
    totalRatings: 150,
    completedBookings: 430,
    isAvailable: true,
    hourlyRate: 240,
    monthlyRate: 3900,
    city: 'Hyderabad',
    area: 'Jubilee Hills',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-16',
    userId: 'u-216',
    name: 'Sampa Das',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Part-time laundry & ironing specialist. Experienced in silk sari & formal suit care.',
    experienceYears: 6,
    services: ['Steam Ironing', 'Silk Care', 'Laundry Wash', 'Folding'],
    skills: ['Steam Ironing', 'Fabric Safety'],
    languages: ['Bengali', 'Hindi'],
    averageRating: 4.86,
    totalRatings: 92,
    completedBookings: 270,
    isAvailable: true,
    hourlyRate: 200,
    monthlyRate: 3100,
    city: 'Kolkata',
    area: 'Howrah',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-17',
    userId: 'u-217',
    name: 'Shoba Rani',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    bio: 'Move-in move-out apartment deep scrubbing & cupboard sanitization maid.',
    experienceYears: 7,
    services: ['Move-in Clean', 'Deep Scrubbing', 'Balcony Washing'],
    skills: ['Deep Scrubbing', 'Fast Work'],
    languages: ['Tamil', 'English'],
    averageRating: 4.89,
    totalRatings: 118,
    completedBookings: 350,
    isAvailable: true,
    hourlyRate: 250,
    monthlyRate: 4100,
    city: 'Chennai',
    area: 'Anna Nagar',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-18',
    userId: 'u-218',
    name: 'Pravin Kumar',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Industrial vacuuming & sofa dry cleaning specialist using professional equipment.',
    experienceYears: 5,
    services: ['Sofa Dry Clean', 'Carpet Vacuum', 'Matress Sanitization'],
    skills: ['Machine Vacuuming', 'Stain Removal'],
    languages: ['Hindi', 'English'],
    averageRating: 4.82,
    totalRatings: 80,
    completedBookings: 230,
    isAvailable: true,
    hourlyRate: 280,
    monthlyRate: 4600,
    city: 'Delhi NCR',
    area: 'Gurugram Sec 28',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'maid-19',
    userId: 'u-219',
    name: 'Pushpa Pawar',
    avatar: 'https://images.unsplash.com/photo-1563306406-e66174fa3787?auto=format&fit=crop&w=300&q=80',
    bio: 'Festive Diwali & Ganpati deep cleaning expert. High enthusiasm and thorough perfection.',
    experienceYears: 8,
    services: ['Festive Deep Clean', 'Kitchen Clean', 'Window Washing'],
    skills: ['High Energy', 'Thorough Cleaning'],
    languages: ['Marathi', 'Hindi'],
    averageRating: 4.94,
    totalRatings: 165,
    completedBookings: 470,
    isAvailable: true,
    hourlyRate: 260,
    monthlyRate: 4200,
    city: 'Mumbai',
    area: 'Dadarm',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-20',
    userId: 'u-220',
    name: 'Vimla Bai',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=300&q=80',
    bio: 'Quiet & trustworthy daily housemaid for senior citizen homes with compassionate attitude.',
    experienceYears: 9,
    services: ['Elderly Home Care', 'Gentle Cleaning', 'Utensil Washing'],
    skills: ['Compassionate', 'Honest', 'Polite'],
    languages: ['Hindi', 'Gujarati'],
    averageRating: 4.96,
    totalRatings: 178,
    completedBookings: 490,
    isAvailable: true,
    hourlyRate: 220,
    monthlyRate: 3500,
    city: 'Mumbai',
    area: 'Borivali West',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-21',
    userId: 'u-221',
    name: 'Bhawna Sharma',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Modern housekeeping maid skilled in eco-friendly chemical-free cleaning products.',
    experienceYears: 4,
    services: ['Eco Cleaning', 'Dusting', 'Floor Care', 'Dishes'],
    skills: ['Eco-friendly', 'Safety Conscious'],
    languages: ['Hindi', 'English'],
    averageRating: 4.76,
    totalRatings: 68,
    completedBookings: 200,
    isAvailable: true,
    hourlyRate: 210,
    monthlyRate: 3300,
    city: 'Bengaluru',
    area: 'Sarjapur Road',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-22',
    userId: 'u-222',
    name: 'Deepa Roy',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    bio: 'Efficient 1.5-hour dishwashing & kitchen scrubbing maid for working couples.',
    experienceYears: 5,
    services: ['Dishwashing', 'Sink Sanitization', 'Countertop Clean'],
    skills: ['Punctual', 'Clean Sink Guarantee'],
    languages: ['Bengali', 'Hindi'],
    averageRating: 4.8,
    totalRatings: 84,
    completedBookings: 250,
    isAvailable: true,
    hourlyRate: 190,
    monthlyRate: 2900,
    city: 'Kolkata',
    area: 'Jadavpur',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-23',
    userId: 'u-223',
    name: 'Sarla Devi',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    bio: 'Comprehensive balcony plant watering, dusting & floor mopping maid.',
    experienceYears: 6,
    services: ['Balcony Cleaning', 'Plant Watering', 'Dusting', 'Floor Mopping'],
    skills: ['Plant Care', 'Clean Sweep'],
    languages: ['Hindi'],
    averageRating: 4.82,
    totalRatings: 90,
    completedBookings: 270,
    isAvailable: true,
    hourlyRate: 200,
    monthlyRate: 3200,
    city: 'Hyderabad',
    area: 'Kukatpally',
    gender: 'Female',
    verified: true,
  },
  {
    id: 'maid-24',
    userId: 'u-224',
    name: 'Santosh Pawar',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    bio: 'Heavy commercial & residential garage, balcony & window glass washer.',
    experienceYears: 7,
    services: ['Glass Cleaning', 'Garage Scrub', 'Window Polishing'],
    skills: ['Physical Strength', 'High Windows'],
    languages: ['Marathi', 'Hindi'],
    averageRating: 4.87,
    totalRatings: 110,
    completedBookings: 320,
    isAvailable: true,
    hourlyRate: 260,
    monthlyRate: 4300,
    city: 'Pune',
    area: 'Baner',
    gender: 'Male',
    verified: true,
  },
  {
    id: 'maid-25',
    userId: 'u-225',
    name: 'Renu Bala',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Punctual morning 7 AM dishwashing and sweeping maid for early risers & office workers.',
    experienceYears: 6,
    services: ['Early Morning Shift', 'Utensil Washing', 'Sweeping'],
    skills: ['Early Morning Punctuality', 'Quiet'],
    languages: ['Hindi', 'Punjabi'],
    averageRating: 4.88,
    totalRatings: 105,
    completedBookings: 310,
    isAvailable: true,
    hourlyRate: 210,
    monthlyRate: 3300,
    city: 'Delhi NCR',
    area: 'Chandni Chowk',
    gender: 'Female',
    verified: true,
  },
];

export const MOCK_REVIEWS: ICustomerReview[] = [
  {
    id: 'rev-1',
    customerName: 'Ananya Deshmukh',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'Chef Ramesh prepared an extraordinary 5-course North Indian meal for our family anniversary! Punctual, neat, and delicious food.',
    serviceType: 'Cook Service',
    date: '2 days ago',
  },
  {
    id: 'rev-2',
    customerName: 'Vikram & Sneha Mehta',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'Sunita is polite, extremely hardworking, and transformed our apartment with deep cleaning. Highly recommended service!',
    serviceType: 'Maid Service',
    date: '1 week ago',
  },
  {
    id: 'rev-3',
    customerName: 'Karan Malhotra',
    customerAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'The booking process was effortless. We booked Priya for a weekly thali plan and the food quality is top-notch!',
    serviceType: 'Cook Service',
    date: '2 weeks ago',
  },
  {
    id: 'rev-4',
    customerName: 'Pooja Hegde',
    customerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'Having a verified maid coming on time every single day has saved our family so much time. Transparent pricing and great support!',
    serviceType: 'Daily Maid Service',
    date: '3 days ago',
  },
  {
    id: 'rev-5',
    customerName: 'Rajesh Iyer',
    customerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'The Cook + Maid combo is a game changer! Both staff members arrived prompt, polite, and background check verified.',
    serviceType: 'Cook + Maid Combo',
    date: '5 days ago',
  },
];

export const MOCK_STATS = [
  { value: '5,000+', label: 'Verified Helpers' },
  { value: '50,000+', label: 'Bookings Completed' },
  { value: '4.9 ★', label: 'Average Rating' },
  { value: '99.8%', label: 'On-time Arrival' },
];

export const MOCK_FAQS: IFaqItem[] = [
  {
    id: 'faq-1',
    question: 'How are the Cooks and Maids background verified?',
    answer: 'All service providers undergo a strict 3-level verification process: Government ID validation (Aadhaar/PAN), Police Record Clearance, and physical address verification with 2 reference checks.',
    category: 'Safety & Verification',
  },
  {
    id: 'faq-2',
    question: 'What happens if my assigned Cook or Maid is unavailable?',
    answer: 'We guarantee a 100% free immediate replacement helper within 60 minutes if your regular staff member takes leave or is unavailable.',
    category: 'Bookings & Replacement',
  },
  {
    id: 'faq-3',
    question: 'Can I request a trial session before committing to a monthly subscription?',
    answer: 'Yes! You can book a 1-day or single-meal trial service to taste the food or evaluate housekeeping before choosing a monthly plan.',
    category: 'Trial & Pricing',
  },
  {
    id: 'faq-4',
    question: 'Are ingredients provided by the cook or home owner?',
    answer: 'For regular home cook service, the home owner provides the raw groceries and spices. However, for party catering or special packages, our chef can bring premium ingredients.',
    category: 'Cook Services',
  },
  {
    id: 'faq-5',
    question: 'What cleaning supplies are required for house maid service?',
    answer: 'Standard daily maid services use your preferred household detergents and mop tools. For deep cleaning packages, our team brings professional-grade tools & eco-friendly chemicals.',
    category: 'Maid Services',
  },
  {
    id: 'faq-6',
    question: 'How does payment and pricing work?',
    answer: 'You pay securely via UPI, Cards, or NetBanking with zero hidden commissions. Monthly plans are billed at the end of each billing cycle with itemized attendance.',
    category: 'Payments',
  },
];

export const MOCK_CITIES = ['Bengaluru', 'Mumbai', 'Delhi NCR', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata'];
export const MOCK_LANGUAGES = ['Hindi', 'English', 'Kannada', 'Marathi', 'Tamil', 'Telugu', 'Bengali', 'Punjabi', 'Gujarati', 'Malayalam'];
